version: "3"

services:
  node:
    container_name: node
    image: "terra-money/localnet-core"
    environment:
      - DEBUG=1
      - ID=0
      - LOG=${LOG:-core.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
      - "2345:2345"
    volumes:
      - ./.testnets:/terrad/data:Z
    networks:
      localnet:
        ipv4_address: 192.168.15.20

  node_1:
    container_name: node_1
    image: "terra-money/localnet-core"
    environment:
      - DEBUG=0
      - ID=1
      - LOG=${LOG:-core.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
      - "2346:2345"
    volumes:
      - ./.testnets:/terrad/data:Z
    networks:
      localnet:
        ipv4_address: 192.168.15.21

  node_2:
    container_name: node_2
    image: "terra-money/localnet-core"
    environment:
      - DEBUG=0
      - ID=2
      - LOG=${LOG:-core.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26676-26677:26656-26657"
      - "1319:1317"
      - "9092:9090"
      - "2347:2345"
    volumes:
      - ./.testnets:/terrad/data:Z
    networks:
      localnet:
        ipv4_address: 192.168.15.22

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.15.0/25